name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Compile pioasm
        run: |
          apt update;
          apt install -y git make cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential;
          git clone https://github.com/raspberrypi/pico-sdk.git --branch master;
          cd pico-sdk;
          git submodule update --init;
          cd ..;
          mkdir pioasm_build;
          cd pioasm_build;
          cmake ../pico-sdk/tools/pioasm;
          make;
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:image"
          file: Dockerfile
          push: true
          tags: endail/pioasm-action-image:latest